<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends EntityRepository
{
    public function findAllOrderedByIdDesc()
    {
        return $this->getEntityManager()->createQuery(
            "SELECT t FROM AppBundle:Tweet t ORDER BY t.id DESC"
        )->getResult();
    }
}
